### ISSUE TITLE
Parameter for the number of pages

### ISSUE THREAD

**Issue by Btibert3** [stattleship/stattleship-r#1]
Should `stattle` include a parameter to limit the number of pages called when `walk

**Comment by batpigandme** [comment]
Just about to report same after running the demo for `tripdubs = stattle(sport=sport, league=league, ep=ep, query=q_body, version=1, walk=TRUE)`, and stopping it before collecting 300 pages— maybe in the interim we should default to `walk=FALSE` for the demo?

**Comment by Btibert3** [comment]
I just changed the README for that, but yeah, we should talk about this at some point.  Coupled with that, it's highly possible that the calls will be throttled also.  This issue is to help solve/guard this.

**Comment by batpigandme** [comment]
Just wrote to david that we might want to add ability to filter by season. Right now it's returning all the triple doubles (unless there have been 6,000 this season which, and I haven't double checked this, I'm pretty sure has not occurred).

**Comment by Btibert3** [comment]
I am going to close this for now.  As we add filters and other issues, this will be less of an issue.  We can always re-open this should we want to include a `maxPages` option
