### ISSUE TITLE
API Endpoint Needs Updating in R Wrapper

### ISSUE THREAD

**Issue by torch77** [stattleship/stattleship-r#34]
Great work so far, I've only played around with the API via the R Wrapper for a couple of days so far but it's awesome. However, I did notice that yesterday the following code stopped working

``` R
q_body <- list(interval_type = "week", status="ended")
test <- ss_get_result(token, sport = "football",
                      league = "nfl", ep = "game_logs", query = q_body, 
                      verbose = T)
```

It was returning the following error 

```
[1] "Making initial API request"
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html>   <head>
                     (right here) ------^
```

After poking around in the source code a bit, it looks like the URL you're concatenating in line 155 (below) of the ss_get_result.R function needs to be updated to the new API endpoint. 

``` R
  ## build the URL and the endpoint
  URL <- sprintf("https://www.stattleship.com/%s/%s/%s", sport, league, ep)
```

I forked the repo and updated it myself to api.stattleship.com and it looks like its working fine again.

**Comment by Btibert3** [comment]
Can you add a Pull request so we can review the code.  Seems straight forward enough, but just want to take a quick look. Thanks!

**Comment by torch77** [comment]
No problem, just submitted it.

**Comment by torch77** [comment]
Looks like the master has the correct URL now, thanks for updating it guys.
