### ISSUE TITLE
Change `stattle` function name to `ssGetResult`

### ISSUE THREAD

**Issue by tcash21** [stattleship/stattleship-r#8]
Makes more sense and follows typical standard of RJDB, RODBC, RPostgreSQL, etc. database packages.

**Comment by Btibert3** [comment]
Do you want me to tackle verbose=T when we change from `stattle` to `ssGetResult`?  Right now it's just an empty option that does nothing.

**Comment by tcash21** [comment]
Sure, maybe verbose=F can conceal those 'fetching page x of N' messages as
well.

**Comment by Btibert3** [comment]
right now verbose isn't being used.  I originally used it for debugging.  Maybe I change the option to `debug`.  We could pass that to `.queryAPI` to help look at the raw response (its a list of 2, the response object and the parsed data).  We could then use verbose in `ssGetResults` for a flag to turn messages on/off?

**Comment by tcash21** [comment]
Yea I think that makes sense. I think by default we keep the paging
messages unless turned off, as I like to know what's going on if something
isn't returning a result right away.

**Comment by batpigandme** [comment]
Second that motion- I would have pulled down 300 pages of triple doubles
this morning if I was flying page-blind

**Comment by Btibert3** [comment]
Addressed in https://github.com/stattleship/stattleship-r/pull/12.  Verbose=TRUE on `ssGetResult` will print the results for you, and stattle is now `ssGetResult`
